---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: docker-install-dir.yml
  when: custom_install

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

#- name: Ensure Docker is started and enabled at boot.
#  service:
#    name: docker
#    state: "{{ docker_service_state }}"
#    enabled: "{{ docker_service_enabled }}"

#- name: Ensure handlers are notified now to avoid firewall conflicts.
#  meta: flush_handlers

- include_tasks: docker-systemd.yml
  when: custom_install

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users
